function taoChapter(tongChapter, chapterDacBiet = []) {
  const ds = [];
  for (let i = tongChapter; i >= 1; i--) {
    ds.push({
      so: i,
      ngay: "--/--/----",
      isMoi: false,
    });
  }
  chapterDacBiet.forEach((chapter) => {
    const index = ds.findIndex((c) => c.so === chapter.so);
    if (index !== -1) {
      ds[index] = {
        ...ds[index],
        ...chapter,
      };
    }
  });

  return ds;
}
const danhSachTruyen = [
  {
    id: 1,
    ten: "Thanh Gươm Diệt Quỷ",
    tenKhac: ["Kimetsu no Yaiba", "鬼滅の刃", "Demon Slayer"],
    tacGia: "Koyoharu Gotouge",
    tinhTrang: "Hoàn Thành",
    theLoai: ["Drama", "Fantasy", "Manga", "Shounen"],
    luotXem: "18,500,000",
    luotTheo: "1,200,000",
    diemDanhGia: 4.9,
    anhBia:
      "https://phongvu.vn/cong-nghe/wp-content/uploads/2025/08/hinh-nen-thanh-guom-diet-quy-55-576x1024.jpg",
    moTa: "Tanjiro là một cậu bé hiền lành sống cùng gia đình ở vùng núi, cho đến ngày cả nhà bị quỷ tàn sát, chỉ còn em gái Nezuko sống sót nhưng đã biến thành quỷ. Tanjiro gia nhập Diệt Quỷ Đội, quyết tâm tìm cách biến Nezuko trở lại con người và trả thù cho gia đình.",
    danhSachChapter: taoChapter(205, [
      { so: 205, ngay: "01/07/2026", isMoi: true },
    ]),
    binhLuan: [],
  },
  {
    id: 2,
    ten: "Chú Thuật Hồi Chiến",
    tenKhac: ["Jujutsu Kaisen", "呪術廻戦", "JJK"],
    tacGia: "Gege Akutami",
    tinhTrang: "Đang Ra",
    theLoai: ["Action", "Fantasy", "Shounen", "Horror"],
    luotXem: "15,200,000",
    luotTheo: "980,000",
    diemDanhGia: 4.8,
    anhBia:
      "https://t.ctcdn.com.br/BgnIXmwrGYCtXF919pg8qHMgTfo=/600x600/smart/i975461.jpeg",
    moTa: ` Yuji Itadori là một học sinh trung học bình thường với sức mạnh
              thể chất phi thường. Cuộc đời cậu thay đổi hoàn toàn khi cậu vô
              tình nuốt một ngón tay của Ryomen Sukuna — vị vua nguyền của thế
              giới chú thuật. Thay vì bị tiêu diệt, Yuji trở thành vật chứa của
              Sukuna và được nhận vào Trường Kỹ Thuật Chú Thuật Đô Thị Tokyo để
              trở thành một pháp sư chú thuật. Tại đây, cùng với Megumi
              Fushiguro và Nobara Kugisaki, Yuji bước vào thế giới nguy hiểm của
              những lời nguyền và chú thuật, đối mặt với những kẻ thù ngày càng
              mạnh hơn trong hành trình tìm kiếm tất cả các ngón tay của Sukuna
              để tiêu diệt chúng mãi mãi.`,
    danhSachChapter: taoChapter(266, [
      { so: 266, ngay: "20/06/2026", isMoi: true },
      { so: 265, ngay: "13/06/2026", isMoi: true },
      { so: 264, ngay: "06/06/2026", isMoi: true },
      { so: 263, ngay: "30/05/2026", isMoi: true },
    ]),

    binhLuan: [
      {
        ten: "OtakuVN",
        kyTuDau: "O",
        sao: 5,
        thoiGian: "2 giờ trước",
        noiDung: "Chương mới quá đỉnh!",
      },
      {
        ten: "MangaFan",
        kyTuDau: "M",
        sao: 5,
        thoiGian: "5 giờ trước",
        noiDung: "JJK vẫn luôn là bộ manga yêu thích của mình.",
      },
    ],
  },

  {
    id: 3,
    ten: "Thám Tử Conan",
    tenKhac: ["Detective Conan", "名探偵コナン"],
    tacGia: "Gosho Aoyama",
    tinhTrang: "Đang Ra",
    theLoai: [
      "Comedy",
      "Drama",
      "Manga",
      "Romance",
      "School Life",
      "Trinh Thám",
    ],
    luotXem: "22,100,000",
    luotTheo: "1,450,000",
    diemDanhGia: 4.8,
    anhBia:
      "https://i.pinimg.com/736x/af/f1/a3/aff1a34e425f8c69447c0cfda16d1753.jpg",
    moTa: "Thám tử học sinh Shinichi Kudo bị một tổ chức bí ẩn cho uống thuốc độc và biến thành cơ thể trẻ con. Lấy tên giả Conan Edogawa, cậu tiếp tục điều tra các vụ án bí ẩn trong lúc tìm cách trở lại hình dạng ban đầu và lật tẩy tổ chức áo đen.",
    danhSachChapter: taoChapter(1120, [
      { so: 1120, ngay: "28/06/2026", isMoi: true },
    ]),
    binhLuan: [],
  },
  {
    id: 4,
    ten: "Black Clover - Thế Giới Phép Thuật",
    tenKhac: ["Black Clover", "ブラッククローバー"],
    tacGia: "Yuki Tabata",
    tinhTrang: "Hoàn Thành",
    theLoai: ["Action"],
    luotXem: "9,800,000",
    luotTheo: "540,000",
    diemDanhGia: 4.6,
    anhBia: "https://dicasgeeks.com.br/wp-content/uploads/2019/11/capa.jpg",
    moTa: "Asta sinh ra không có phép thuật trong một thế giới mà sức mạnh phép thuật quyết định tất cả. Cùng người bạn/đối thủ Yuno, cậu nuôi mộng trở thành Pháp Sư Vua bằng chính nghị lực và cây kiếm chống phép thuật của mình.",
    danhSachChapter: taoChapter(370),
    binhLuan: [],
  },
  {
    id: 5,
    ten: "Mairimashita! Iruma-kun",
    tenKhac: ["Welcome to Demon School! Iruma-kun"],
    tacGia: "Osamu Nishi",
    tinhTrang: "Đang Ra",
    theLoai: ["Comedy", "Drama", "Fantasy", "Manga", "School Life", "Shounen"],
    luotXem: "6,300,000",
    luotTheo: "310,000",
    diemDanhGia: 4.5,
    anhBia:
      "https://img10.hotstar.com/image/upload/f_auto,q_auto/sources/r1/cms/prod/9439/1734434359439-i",
    moTa: "Cậu bé loài người Iruma bị ông bà vô tình bán cho quỷ, và bất ngờ trở thành cháu cưng của một đại ma vương. Được cho vào học tại trường quỷ, Iruma phải tìm cách sống sót và giấu kín thân phận con người của mình.",
    danhSachChapter: taoChapter(280, [
      { so: 280, ngay: "25/06/2026", isMoi: true },
    ]),
    binhLuan: [],
  },
  {
    id: 6,
    ten: "Wistoria Bản Hùng Ca Kiếm Và Pháp Trượng",
    tenKhac: ["Wistoria: Wand and Sword"],
    tacGia: "Hyun Sub Shin",
    tinhTrang: "Đang Ra",
    theLoai: [
      "Action",
      "Adventure",
      "Fantasy",
      "Comedy",
      "Manga",
      "School Life",
    ],
    luotXem: "2,100,000",
    luotTheo: "150,000",
    diemDanhGia: 4.4,
    anhBia:
      "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx182300-IYkq5KrkQq1V.jpg",
    moTa: "Ở một thế giới mà phép thuật là sức mạnh tối thượng, Will Wagner - người không thể dùng phép thuật - chỉ có thể sử dụng kiếm. Cậu quyết tâm nhập học tại học viện phép thuật danh giá để chứng minh giá trị của bản thân.",
    danhSachChapter: taoChapter(65, [
      { so: 65, ngay: "20/06/2026", isMoi: true },
    ]),
    binhLuan: [],
  },
  {
    id: 7,
    ten: "Blue Lock",
    tenKhac: ["ブルーロック"],
    tacGia: "Muneyuki Kaneshiro, Yusuke Nomura",
    tinhTrang: "Đang Ra",
    theLoai: ["Action", "Sport"],
    luotXem: "8,700,000",
    luotTheo: "620,000",
    diemDanhGia: 4.7,
    anhBia:
      "https://sm.ign.com/t/ign_pk/cover/b/blue-lock-/blue-lock-the-movie-episode-nagi_qgvd.600.jpg",
    moTa: "Sau thất bại ở World Cup, Liên đoàn bóng đá Nhật Bản lập ra dự án Blue Lock nhằm đào tạo một tiền đạo ích kỷ nhất, giỏi nhất thế giới. 300 cầu thủ trẻ tài năng bước vào cuộc cạnh tranh sinh tử để giành lấy một suất duy nhất.",
    danhSachChapter: taoChapter(280, [
      { so: 280, ngay: "22/06/2026", isMoi: true },
    ]),
    binhLuan: [],
  },
  {
    id: 8,
    ten: "Captain Tsubasa: Rising Sun",
    tenKhac: ["キャプテン翼"],
    tacGia: "Yoichi Takahashi",
    tinhTrang: "Đang Ra",
    theLoai: ["Manga", "Sport"],
    luotXem: "3,400,000",
    luotTheo: "190,000",
    diemDanhGia: 4.3,
    anhBia:
      "https://play-lh.googleusercontent.com/h9W8nSt2ZbzlmihOsqneMa7BWKVcIq7oRvUH3xq1GMgV4tSLOapAJzL6hgE0gEhVtdlTKiTbh9gGNo6W44Gh",
    moTa: "Tsubasa Oozora cùng đồng đội bước vào giai đoạn mới của sự nghiệp bóng đá, hướng tới những giải đấu đỉnh cao của thế giới với ước mơ vô địch World Cup.",
    danhSachChapter: taoChapter(45),
    binhLuan: [],
  },
  {
    id: 9,
    ten: "Tôi Mộng Giữa Ban Ngày",
    tenKhac: [],
    tacGia: "Đang cập nhật",
    tinhTrang: "Đang Ra",
    theLoai: ["Manhua", "Ngôn Tình", "School Life", "Truyện Màu"],
    luotXem: "1,250,000",
    luotTheo: "88,000",
    diemDanhGia: 4.2,
    anhBia:
      "https://moonnovel.store/wp-content/uploads/2025/10/1n-698x1024.webp",
    moTa: "Một câu chuyện tình cảm học đường nhẹ nhàng, xoay quanh những rung động đầu đời và những giấc mơ ban ngày của nhân vật chính. (Mô tả tạm — cập nhật khi có nội dung gốc.)",
    danhSachChapter: taoChapter(40, [
      { so: 40, ngay: "18/06/2026", isMoi: true },
    ]),
    binhLuan: [],
  },
  {
    id: 10,
    ten: "Còn Ra Thể Thống Gì Nữa",
    tenKhac: [],
    tacGia: "Đang cập nhật",
    tinhTrang: "Đang Ra",
    theLoai: ["Action"],
    luotXem: "980,000",
    luotTheo: "62,000",
    diemDanhGia: 4.1,
    anhBia:
      "https://static2.vieon.vn/vieplay-image/poster_v4/2026/02/09/ehwpq0wc_660x946-conrathethongginua.png",
    moTa: "Nhân vật chính bị đẩy vào những tình huống dở khóc dở cười, phải xoay xở để giữ vững vị thế và danh dự của mình. (Mô tả tạm — cập nhật khi có nội dung gốc.)",
    danhSachChapter: taoChapter(30, [
      { so: 30, ngay: "15/06/2026", isMoi: true },
    ]),
    binhLuan: [],
  },
  {
    id: 11,
    ten: "Thế Giới Sau Tận Thế",
    tenKhac: [],
    tacGia: "Đang cập nhật",
    tinhTrang: "Đang Ra",
    theLoai: ["Action", "Comedy", "Manhwa", "Truyện Màu"],
    luotXem: "1,600,000",
    luotTheo: "105,000",
    diemDanhGia: 4.3,
    anhBia: "https://i.redd.it/ws2ml66sx55h1.jpeg",
    moTa: "Sau thảm họa hủy diệt nhân loại, những người sống sót phải thích nghi với một thế giới đầy nguy hiểm nhưng cũng không thiếu tiếng cười. (Mô tả tạm — cập nhật khi có nội dung gốc.)",
    danhSachChapter: taoChapter(55, [
      { so: 55, ngay: "24/06/2026", isMoi: true },
    ]),
    binhLuan: [],
  },
  {
    id: 12,
    ten: "Ma Vương Tái Sinh Trở Thành Pháp Sư Mạnh Nhất",
    tenKhac: [],
    tacGia: "Đang cập nhật",
    tinhTrang: "Đang Ra",
    theLoai: ["Action", "Adventure", "Fantasy", "Manga", "Romance"],
    luotXem: "2,050,000",
    luotTheo: "134,000",
    diemDanhGia: 4.4,
    anhBia: "img/tt6.jpg",
    moTa: "Một ma vương bị đánh bại tái sinh vào thân phận một pháp sư yếu đuối, quyết tâm dùng kinh nghiệm và trí tuệ của mình để một lần nữa vươn lên đỉnh cao sức mạnh. (Mô tả tạm — cập nhật khi có nội dung gốc.)",
    danhSachChapter: taoChapter(48, [
      { so: 48, ngay: "21/06/2026", isMoi: true },
    ]),
    binhLuan: [],
  },
  {
    id: 13,
    ten: "Bạo Thực Giả",
    tenKhac: [],
    tacGia: "Đang cập nhật",
    tinhTrang: "Đang Ra",
    theLoai: ["Action"],
    luotXem: "890,000",
    luotTheo: "51,000",
    diemDanhGia: 4.0,
    anhBia: "https://truyenqq.com.vn/media/book/bao-thuc-gia.png",
    moTa: "Nhân vật chính sở hữu năng lực đặc biệt liên quan đến việc 'ăn' sức mạnh của kẻ khác, từng bước trở thành hiểm họa mà không ai dám xem thường. (Mô tả tạm — cập nhật khi có nội dung gốc.)",
    danhSachChapter: taoChapter(25, [
      { so: 25, ngay: "19/06/2026", isMoi: true },
    ]),
    binhLuan: [],
  },
  {
    id: 14,
    ten: "Bá Vương Sủng Ái Cô Vợ Mù",
    tenKhac: [],
    tacGia: "Đang cập nhật",
    tinhTrang: "Đang Ra",
    theLoai: ["Chuyển Sinh", "Manhwa", "Ngôn Tình", "Truyện Màu"],
    luotXem: "1,780,000",
    luotTheo: "142,000",
    diemDanhGia: 4.5,
    anhBia: "img/tt1.png",
    moTa: "Sau khi chuyển sinh vào một thân phận mới, nữ chính khiếm thị nhận được sự che chở tuyệt đối từ vị bá vương lạnh lùng nhưng si tình. (Mô tả tạm — cập nhật khi có nội dung gốc.)",
    danhSachChapter: taoChapter(60, [
      { so: 60, ngay: "23/06/2026", isMoi: true },
    ]),
    binhLuan: [],
  },
  {
    id: 15,
    ten: "Ác Chi Hoàn",
    tenKhac: [],
    tacGia: "Đang cập nhật",
    tinhTrang: "Đang Ra",
    theLoai: ["Action"],
    luotXem: "670,000",
    luotTheo: "38,000",
    diemDanhGia: 3.9,
    anhBia:
      "https://panomic1.info/wp-content/uploads/2026/04/z7754738904501_a90173d77d1d74041c4a64cf5af3a9eb-720x970.webp",
    moTa: "Một câu chuyện hành động u tối xoay quanh những thế lực đối đầu và những âm mưu ẩn giấu phía sau. (Mô tả tạm — cập nhật khi có nội dung gốc.)",
    danhSachChapter: taoChapter(20, [
      { so: 20, ngay: "26/06/2026", isMoi: true },
    ]),
    binhLuan: [],
  },
  {
    id: 16,
    ten: "Thế Giới Này Không Tồn Tại Ma Quỷ",
    tenKhac: [],
    tacGia: "Đang cập nhật",
    tinhTrang: "Đang Ra",
    theLoai: ["Action"],
    luotXem: "540,000",
    luotTheo: "29,000",
    diemDanhGia: 3.8,
    anhBia: "img/tt2.png",
    moTa: "Nhân vật chính khám phá ra sự thật đằng sau một thế giới tưởng chừng bình yên, nơi ranh giới giữa con người và quỷ dữ mờ nhạt hơn ai nghĩ. (Mô tả tạm — cập nhật khi có nội dung gốc.)",
    danhSachChapter: taoChapter(18),
    binhLuan: [],
  },
  {
    id: 17,
    ten: "Phát Sóng Của Siêu Việt Giả",
    tenKhac: [],
    tacGia: "Đang cập nhật",
    tinhTrang: "Đang Ra",
    theLoai: ["Action"],
    luotXem: "710,000",
    luotTheo: "44,000",
    diemDanhGia: 4.0,
    anhBia: "img/tt3.png",
    moTa: "Một streamer bí ẩn phát sóng những trận chiến sinh tử của mình, thu hút hàng triệu người xem theo dõi từng bước đi trên con đường vượt qua giới hạn. (Mô tả tạm — cập nhật khi có nội dung gốc.)",
    danhSachChapter: taoChapter(22, [
      { so: 22, ngay: "17/06/2026", isMoi: true },
    ]),
    binhLuan: [],
  },
  {
    id: 18,
    ten: "Tỏ Tình",
    tenKhac: [],
    tacGia: "Đang cập nhật",
    tinhTrang: "Đang Ra",
    theLoai: ["Manhua", "Ngôn Tình", "Romance", "Truyện Màu"],
    luotXem: "1,020,000",
    luotTheo: "76,000",
    diemDanhGia: 4.2,
    anhBia: "img/tt4.png",
    moTa: "Một câu chuyện tình cảm lãng mạn xoay quanh những lời tỏ tình vụng về nhưng chân thành của tuổi trẻ. (Mô tả tạm — cập nhật khi có nội dung gốc.)",
    danhSachChapter: taoChapter(35, [
      { so: 35, ngay: "16/06/2026", isMoi: true },
    ]),
    binhLuan: [],
  },
  {
    id: 19,
    ten: "Sức Mạnh Tối Đa? Ta Lại Là Vong Linh Sư",
    tenKhac: [],
    tacGia: "Đang cập nhật",
    tinhTrang: "Đang Ra",
    theLoai: ["Manhua", "Action", "Truyện Màu"],
    luotXem: "1,340,000",
    luotTheo: "97,000",
    diemDanhGia: 4.3,
    anhBia: "img/tt5.png",
    moTa: "Nhân vật chính thức tỉnh sức mạnh tưởng chừng vô dụng của Vong Linh Sư, để rồi phát hiện ra đây mới chính là sức mạnh tối thượng bị lãng quên. (Mô tả tạm — cập nhật khi có nội dung gốc.)",
    danhSachChapter: taoChapter(38, [
      { so: 38, ngay: "14/06/2026", isMoi: true },
    ]),
    binhLuan: [],
  },
  {
    id: 20,
    ten: "Kiếm Thực",
    tenKhac: [],
    tacGia: "Đang cập nhật",
    tinhTrang: "Sắp Ra Mắt",
    theLoai: ["Action"],
    luotXem: "0",
    luotTheo: "0",
    diemDanhGia: 0,
    anhBia: "img/tt8.png",
    moTa: "Truyện sắp ra mắt — nội dung sẽ được cập nhật khi phát hành chương đầu tiên.",
    danhSachChapter: [],
    binhLuan: [],
  },
  {
    id: 21,
    ten: "Cuộc Sống Hiện Đại Của Đấng Tối Cao",
    tenKhac: [],
    tacGia: "Đang cập nhật",
    tinhTrang: "Sắp Ra Mắt",
    theLoai: ["Action"],
    luotXem: "0",
    luotTheo: "0",
    diemDanhGia: 0,
    anhBia: "img/tt7.jpg",
    moTa: "Truyện sắp ra mắt — nội dung sẽ được cập nhật khi phát hành chương đầu tiên.",
    danhSachChapter: [],
    binhLuan: [],
  },
  {
    id: 22,
    ten: "Top Ranker",
    tenKhac: [],
    tacGia: "Đang cập nhật",
    tinhTrang: "Sắp Ra Mắt",
    theLoai: ["Action"],
    luotXem: "0",
    luotTheo: "0",
    diemDanhGia: 0,
    anhBia: "img/tt9.png",
    moTa: "Truyện sắp ra mắt — nội dung sẽ được cập nhật khi phát hành chương đầu tiên.",
    danhSachChapter: [],
    binhLuan: [],
  },
  {
    id: 23,
    ten: "Chiện Lược Chinh Phục Tòa Tháp Của Gã Hanam",
    tenKhac: [],
    tacGia: "Đang cập nhật",
    tinhTrang: "Sắp Ra Mắt",
    theLoai: ["Action"],
    luotXem: "0",
    luotTheo: "0",
    diemDanhGia: 0,
    anhBia: "img/tt10.png",
    moTa: "Truyện sắp ra mắt — nội dung sẽ được cập nhật khi phát hành chương đầu tiên.",
    danhSachChapter: [],
    binhLuan: [],
  },
  {
    id: 24,
    ten: "Sinh Tồn Với Tư Cách Là Một Huyết Vương",
    tenKhac: [],
    tacGia: "Đang cập nhật",
    tinhTrang: "Đang Ra",
    theLoai: ["Action"],
    luotXem: "620,000",
    luotTheo: "41,000",
    diemDanhGia: 4.0,
    anhBia: "img/tt12.png",
    moTa: "Nhân vật chính thức tỉnh thành huyết vương giữa một thế giới đầy nguy hiểm, phải học cách sinh tồn và kiểm soát sức mạnh mới của mình. (Mô tả tạm — cập nhật khi có nội dung gốc.)",
    danhSachChapter: taoChapter(28, [
      { so: 28, ngay: "13/06/2026", isMoi: true },
    ]),
    binhLuan: [],
  },
  {
    id: 25,
    ten: "Cách Thức Sinh Tồn Của Pháo Hôi Khuê Nữ",
    tenKhac: [],
    tacGia: "Đang cập nhật",
    tinhTrang: "Đang Ra",
    theLoai: ["Cổ Đại", "Manhua", "Ngôn Tình", "Truyện Màu", "Xuyên Không"],
    luotXem: "870,000",
    luotTheo: "59,000",
    diemDanhGia: 4.1,
    anhBia: "img/tt13.png",
    moTa: "Xuyên không vào một tiểu thuyết cổ đại với vai một nhân vật phụ có số phận bi thảm, nữ chính quyết tâm thay đổi vận mệnh của mình bằng trí tuệ và sự khôn khéo. (Mô tả tạm — cập nhật khi có nội dung gốc.)",
    danhSachChapter: taoChapter(33, [
      { so: 33, ngay: "12/06/2026", isMoi: true },
    ]),
    binhLuan: [],
  },
  {
    id: 26,
    ten: "Toàn Dân Chuyển Chức Duy Ta Vô Chức Tàn Nhẫn",
    tenKhac: [],
    tacGia: "Đang cập nhật",
    tinhTrang: "Đang Ra",
    theLoai: ["Action", "Chuyển Sinh", "Manhua", "Truyện Màu", "Xuyên Không"],
    luotXem: "1,450,000",
    luotTheo: "112,000",
    diemDanhGia: 4.3,
    anhBia: "img/tt11.png",
    moTa: "Khi cả nhân loại được ban cho chức nghiệp đặc biệt, nhân vật chính lại là người duy nhất không có chức nghiệp nào — buộc phải tìm ra con đường sinh tồn của riêng mình. (Mô tả tạm — cập nhật khi có nội dung gốc.)",
    danhSachChapter: taoChapter(42, [
      { so: 42, ngay: "11/06/2026", isMoi: true },
    ]),
    binhLuan: [],
  },
  {
    id: 27,
    ten: "Phối Sắc Giã",
    tenKhac: [],
    tacGia: "Đang cập nhật",
    tinhTrang: "Đang Ra",
    theLoai: ["Action"],
    luotXem: "480,000",
    luotTheo: "27,000",
    diemDanhGia: 3.8,
    anhBia:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgdHCv00x-sIEPnpm6NvBW6FO4QwM_o72ZHA&s",
    moTa: "Một câu chuyện hành động xoay quanh những kỹ năng và bí thuật đặc biệt của nhân vật chính. (Mô tả tạm — cập nhật khi có nội dung gốc.)",
    danhSachChapter: taoChapter(15),
    binhLuan: [],
  },

  /*Them truyen khac tai day*/
];
function layTruyenTheoId(id) {
  return danhSachTruyen.find((truyen) => truyen.id === id);
}
function layTruyenLienQuan(idHienTai, soLuong = 4) {
  return danhSachTruyen
    .filter((truyen) => truyen.id !== idHienTai)
    .slice(0, soLuong);
}
